# Netlify Configuration
# For deploying Next.js applications

[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

# Redirect all requests to Next.js
[[redirects]]
  from = "/*"
  to = "/"
  status = 200
  force = false

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()"

# Cache static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variable configuration
# Set these in Netlify UI: Site Settings > Environment Variables
# Required variables:
# - NEXT_PUBLIC_POCKETBASE_URL (or NEXT_PUBLIC_SUPABASE_URL)
# - GEMINI_API_KEY (or keep existing AI keys)
# - CLOUDINARY_CLOUD_NAME, CLOUDINARY_API_KEY, CLOUDINARY_API_SECRET
# - FIGMA_ACCESS_TOKEN, FIGMA_FILE_KEY (if using Figma integration)

# Functions configuration (if using Netlify Functions)
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Development settings
[dev]
  command = "npm run dev"
  port = 3000
  publish = ".next"
  autoLaunch = false
