name: AI Agent Evaluation - ABACO Financial Intelligence

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'lib/agents/**'
      - 'lib/cosmosdb/**'
      - '__tests__/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'lib/agents/**'
      - 'lib/cosmosdb/**'
      - '__tests__/**'

jobs:
  ai-agent-evaluation:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run AI Toolkit Agent Evaluation
      run: |
        npm run test:agents
        npm run test:coverage -- --testPathPattern=agents
      env:
        NODE_ENV: test
        AZURE_COSMOS_DB_ENDPOINT: ${{ secrets.AZURE_COSMOS_DB_ENDPOINT }}
        AZURE_COSMOS_DB_KEY: ${{ secrets.AZURE_COSMOS_DB_KEY }}

    - name: Upload AI Agent Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ai-agent-test-results
        path: |
          coverage/
          test-results/
        retention-days: 30

    - name: AI Toolkit Tracing Analysis
      run: |
        echo "🤖 AI Agent Performance Analysis"
        echo "Evaluating financial intelligence agent capabilities..."
        npm run analyze:traces
      continue-on-error: true
