name: SonarQube Analysis - Abaco Financial Intelligence Platform
permissions:
  contents: read

on:
  push:
    branches: [ main, develop, feature/* ]
  pull_request:
    branches: [ main, develop ]

env:
  NODE_VERSION: '20'
  SONAR_PROJECT_KEY: 'abaco-financial-intelligence-platform'
  AZURE_TENANT_ID: 'abaco-financial'

jobs:
  quality-analysis:
    name: Code Quality & Security Analysis
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Required for SonarCloud analysis
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm ci
        npm install -g sonar-scanner
    
    - name: Validate environment
      run: |
        echo "Validating Abaco Financial Intelligence Platform environment..."
        node --version
        npm --version
        sonar-scanner --version
    
    - name: TypeScript compilation validation
      run: npx tsc --noEmit --skipLibCheck
    
    - name: ESLint analysis with reporting
      run: npm run lint:report
      continue-on-error: true
    
    - name: Financial Intelligence test suite
      run: npm run test:coverage
      env:
        CI: true
        NODE_ENV: test
        AITK_TRACING_ENABLED: true
        AITK_EVALUATION_MODE: ci
    
    - name: AI Agent evaluation suite
      run: npm run agents:eval
      continue-on-error: true
    
    - name: SonarCloud analysis
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }}
          -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
          -Dsonar.projectName="Abaco Financial Intelligence Platform"
          -Dsonar.sources=./app,./components,./lib,./supabase/functions,./supabase/migrations,./middleware.ts
          -Dsonar.tests=./lib/**/*.test.ts,./app/**/*.test.ts,./components/**/*.test.tsx
          -Dsonar.exclusions=**/node_modules/**,**/*.test.ts,**/*.spec.ts,**/coverage/**,**/*.d.ts,**/dist/**,**/.next/**,**/build/**
          -Dsonar.typescript.lcov.reportPaths=coverage/lcov.info
          -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
          -Dsonar.coverage.exclusions=**/lib/agents/**/*.ts,**/jest.setup.js
          -Dsonar.security.hotspots.checkAll=true
          -Dsonar.qualitygate.wait=true
    
    - name: Quality gate validation
      uses: sonarqube-quality-gate-action@master
      timeout-minutes: 5
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        directory: ./coverage
        flags: financial-intelligence
        name: abaco-financial-coverage
        token: ${{ secrets.CODECOV_TOKEN }}
    
    - name: Archive analysis artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: quality-analysis-results
        path: |
          coverage/
          eslint-report.json
          .scannerwork/report-task.txt
        retention-days: 30

  security-scan:
    name: Security & Compliance Scan
    runs-on: ubuntu-latest
    needs: quality-analysis
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Financial platform security audit
      run: |
        echo "Running Abaco Financial Intelligence security audit..."
        npm audit --audit-level high --json > security-audit.json || true
        npm audit --audit-level high
      continue-on-error: true
    
    - name: Dependency vulnerability scan
      run: |
        echo "Scanning for known vulnerabilities in financial platform dependencies..."
        npx audit-ci --config .auditci.json || true
      continue-on-error: true
    
    - name: Archive security reports  
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-reports
        path: |
          security-audit.json
        retention-days: 90
